"""Measures where each Corner Ornament's artwork is actually drawn, and writes
AetherFrame/Domain/Components/ArtCoverageData.g.cs.

A Corner Ornament's artwork sits in a large square box, most of which is transparent (the inner
quadrant, which lies over the Plate's content, is clear in every one). The editors' canvas
selection (issue #115) hit tests the drawing, not the box: a click on a clear part of the box goes
to what is underneath.

Each artwork is cut into a GRID x GRID grid over its whole image. A cell is covered when any pixel
in it has alpha >= ALPHA; covered cells then grow by GROW cells in every direction, so a click on
the very edge of a fine stroke still counts. Each row is written as a 32-bit mask, bit x for
column x (0 = the image's left edge as stored, before any mirroring or rotation the placement
applies). This reads the runtime PNGs and changes none of them.

Usage: python tools/art/measure_coverage.py   (from the repository root; Pillow only)
"""
import glob
import os

from PIL import Image

ROOT = os.path.join("AetherFrame", "Assets")
OUT = os.path.join("AetherFrame", "Domain", "Components", "ArtCoverageData.g.cs")
PATTERNS = (
    os.path.join(ROOT, "Components", "*", "*_CornerOrnament.png"),
    os.path.join(ROOT, "Components", "CelestialDream", "CornerOrnaments", "*.png"),
)

GRID = 32
ALPHA = 32
GROW = 1


def measure(path):
    alpha = Image.open(path).convert("RGBA").getchannel("A")
    width, height = alpha.size
    covered = [[False] * GRID for _ in range(GRID)]
    for row in range(GRID):
        top, bottom = row * height // GRID, (row + 1) * height // GRID
        for column in range(GRID):
            left, right = column * width // GRID, (column + 1) * width // GRID
            if alpha.crop((left, top, right, bottom)).getextrema()[1] >= ALPHA:
                covered[row][column] = True

    grown = [[False] * GRID for _ in range(GRID)]
    for row in range(GRID):
        for column in range(GRID):
            if covered[row][column]:
                for y in range(max(0, row - GROW), min(GRID, row + GROW + 1)):
                    for x in range(max(0, column - GROW), min(GRID, column + GROW + 1)):
                        grown[y][x] = True

    return [sum(1 << x for x in range(GRID) if grown[y][x]) for y in range(GRID)]


def main():
    paths = sorted({p for pattern in PATTERNS for p in glob.glob(pattern)})
    if not paths:
        raise SystemExit("No Corner Ornament artwork found: run from the repository root.")

    lines = [
        "// <auto-generated>",
        "// Written by tools/art/measure_coverage.py from the artwork's pixels: where each Corner Ornament's",
        "// drawing is, as a coarse grid (ArtCoverage). Edit the script and run it again rather than editing this file.",
        "// </auto-generated>",
        "",
        "using System;",
        "using System.Collections.Generic;",
        "",
        "namespace AetherFrame.Domain.Components;",
        "",
        "internal static class ArtCoverageData",
        "{",
        "    /// <summary>Each Corner Ornament artwork's coverage, by its asset path (<see cref=\"BuiltInArtAsset.AssetPath\"/>).</summary>",
        "    internal static readonly IReadOnlyDictionary<string, ArtCoverage> ByAssetPath =",
        "        new Dictionary<string, ArtCoverage>(StringComparer.Ordinal)",
        "        {",
    ]
    for path in paths:
        asset_path = os.path.relpath(path, ROOT).replace(os.sep, "/")
        rows = measure(path)
        lines.append(f"            [\"{asset_path}\"] = new(")
        lines.append("            [")
        for start in range(0, GRID, 8):
            lines.append("                " + ", ".join(f"0x{rows[i]:08X}u" for i in range(start, start + 8)) + ",")
        lines.append("            ]),")

    lines += ["        };", "}", ""]
    with open(OUT, "w", newline="\n", encoding="utf-8") as output:
        output.write("\n".join(lines))
    print(f"Wrote {OUT}: {len(paths)} artworks.")


if __name__ == "__main__":
    main()
